/**
 * Photographs generated for the dishes on the POS menu, one per dish, stored
 * at /img/dishes/<slug>.webp. The database carries no images, so dishes are
 * matched by name; anything added to the menu later falls back to the
 * keyword-matched library in the menu adapter.
 */

const SLUGS = new Set([
  "48-hours-cooked-dal-noorani",
  "achari-butter-fish-tikka",
  "arabic-grilled-fish",
  "avocado-edamame-toast",
  "baked-lasagne",
  "baked-quinoa-casserole",
  "balochi-makhan-murgh-tikka",
  "bbq-miso-mushroom-skewer",
  "blueberry-crumble-cheesecake",
  "blue-pea-vegetable-fried-rice",
  "braised-lamb",
  "cantonese-salt-pepper-prawn",
  "caramel-vanilla-mille-feuille",
  "charred-broccoli",
  "chicken-chilli-oil",
  "chicken-hot-pot",
  "chicken-kulcha",
  "chicken-ragu",
  "chicken-seekh-kebab-on-khamiri-naan",
  "chicken-water-chestnut",
  "chilli-cheese-kulcha",
  "chilli-garlic-chicken",
  "chilli-garlic-fried-rice",
  "chilli-garlic-noodle",
  "chocolate-hazelnut-marjolaine",
  "chow-mein",
  "churrasco-tangri-kebab",
  "cream-cheese-ravioli",
  "cream-cheese-water-chestnut",
  "creamy-mushroom-potato-roasti",
  "creamy-mushroom-spaghetti",
  "curry-ketchup-dutch-fries",
  "fish-65",
  "fish-finger-tempura",
  "four-seasons-vegetable",
  "garden-fresh",
  "garlic-butter-lamb-chops",
  "green-quinoa",
  "grilled-chicken-cheese-pasta",
  "grilled-john-dory",
  "gucchi-galouti",
  "half-roasted-chicken",
  "homemade-potato-wafers",
  "hongkong-style-noodle",
  "hot-burrata",
  "hot-honey-chicken-grilled-corn",
  "indonesian-chicken-satay",
  "jerk-spiced-chicken-kalmi-kebab",
  "john-dory-fish",
  "kale-chicken-caesar",
  "kandhari-red-burrata",
  "khasta-chicken-boti",
  "khasta-dhingri",
  "khasta-mutton-boti",
  "korean-chicken-wings",
  "kung-pao-potato",
  "laal-maas-toastie",
  "lotus-root",
  "lucknowi-bhuna-murgh",
  "masala-chicken-toastie",
  "mezze-platter",
  "millets-tabbouleh",
  "moist-ten-layer-carrot-cake",
  "murgh-makhani",
  "mushroom-risotto",
  "mutton-seekh-kebab",
  "mutton-tikka-amritsari",
  "naples-margherita",
  "orient-spring-roll",
  "ottoman-spinach-feta",
  "palak-patta",
  "paneer-tikka",
  "paneer-tikka-butter-masala",
  "pan-fried-corn-fritter",
  "peri-peri-peanut-chaat",
  "phuket-prawn-chilli-mango",
  "piri-piri-dutch-fries",
  "prawn-butter-garlic",
  "prawn-chives-har-gow",
  "prawn-thermidor",
  "prawn-x-o",
  "rigatoni-vegetable-marinara",
  "roast-lamb-flat-bread",
  "schezwan-paneer",
  "silbatta-palak-paneer",
  "silken-tofu-braised-mushroom",
  "smoked-chicken-vodka-sauce",
  "sourdough-garlic-bread",
  "souvlaki-chicken-kofta",
  "spicy-dragon-chilli-chicken",
  "spicy-dragon-cottage-cheese",
  "spicy-marinara",
  "stir-fry-fish-chilli-basil",
  "stir-fry-green-beans",
  "tandoori-stuffed-potato",
  "thai-cashew-chicken",
  "thai-minced-chicken",
  "thai-mix-meat-fried-rice",
  "tiramisu",
  "truffle-chicken",
  "truffle-dutch-fries",
  "umami-fried-rice",
  "vegetable-black-bean",
  "vietnamese-coffee-brownie",
  "volcano-chicken-kebab",
  "whole-fish-fillet",
]);

export function dishSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function dishImage(name: string): string | undefined {
  const slug = dishSlug(name);
  return SLUGS.has(slug) ? `/img/dishes/${slug}.webp` : undefined;
}
